dist: trusty
sudo: false
language: python
env:
- TOXENV=flake8
- TOXENV=isort
cache: pip
matrix:
  fast_finish: true
  include:
  - python: 3.8
    dist: xenial
    sudo: true
    env: TOXENV=py38-dj3.0-drf3.11
install:
- pip install tox coveralls
script:
- tox
after_success:
- if [ -f .coverage ]; then coveralls; fi
